WIP : Some cosmetic improvements
oufti-playground/devfest-lille-2017 pull request #4
Opened 2017-05-31 09:49 UTC by jmMeessen

I propose the following improvements:

- "sell" => "sales_pitch"
- resized the images/jenkins-cd-orchestrator.jpg to correct the proportions
- added the command to check the installed version (vagrant & virtualbox)

2017-06-01 07:25 UTC, dduportal requested changes

2017-06-01 07:25 UTC, dduportal commented on chapters/04-demoapp.adoc
> +* Clean the window: `clear`
```-bash: clean: command not found``` ;)

+1 for replacing the 1st word, but the shell command is `clear`

2017-06-01 07:25 UTC, dduportal commented on chapters/03-hello.adoc
> +* VirtualBox >= 5.1.18 &nbsp; &nbsp; &nbsp; ("_vboxmanage --version_")
`&nbsp;` should not be used on the source. Asciidoctor provides the `+` char to provide "forced" line returns (unless I misunderstood).
=> I'm not very pleased by pushing too much design in the content. What do you think about adding a sub list item with the command ?
=> Can you make the command to be a source block or inline code ?

2017-06-01 07:25 UTC, dduportal commented on chapters/03-hello.adoc
> +* Vagrant >= 1.9.1  &nbsp; &nbsp; &nbsp; ("_vagrant version_")
Same here: no `&nbsp;` and source code

2017-06-01 07:25 UTC, dduportal commented on chapters/04-demoapp.adoc
> +** Resolve unit test dependencies
I totally agree on the rephrasing. However, the order matters: can you just invert those two rephrased sentences ?

2017-06-01 07:25 UTC, dduportal commented on chapters/04-demoapp.adoc
> +** Resolve packaging dependencies
Same here: invert :)

2017-06-01 07:25 UTC, dduportal commented on chapters/04-demoapp.adoc
> +** Resolve integration test dependencies
Same here, invert :)

2017-06-01 08:26 UTC, jmMeessen commented on chapters/04-demoapp.adoc
> +** Resolve unit test dependencies
removed the resolve line

2017-06-01 08:26 UTC, jmMeessen commented on chapters/04-demoapp.adoc
> +** Resolve packaging dependencies
removed the resolve line

2017-06-01 08:27 UTC, jmMeessen commented on chapters/04-demoapp.adoc
> +** Resolve integration test dependencies
removed the resolve line

2017-06-01 09:55 UTC, jmMeessen commented on chapters/03-hello.adoc
> +* Vagrant >= 1.9.1  &nbsp; &nbsp; &nbsp; ("_vagrant version_")
Changed the presentation

2017-06-02 09:00 UTC, dduportal commented on chapters/03-hello.adoc
> +== prepare lab environment
After thinking about this 2 days, I really don't want to put those commands in a slide: it is "too much" distraction.

I might prefer to put links to vagrant and virtualbox website, and let people search a bit.

2017-06-04 06:28 UTC, dduportal approved these changes

2017-06-04 06:28 UTC, merged